# Generated by Django 3.0.1 on 2020-01-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'admin'), (3, 'superuser')], default=1),
        ),
    ]
